name: Build & Push to Production

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login to aliyun
        uses: jerray/setup-aliyun-cli-action@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          aliyun-cli-version: '3.0.102'
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_REGION }}
      - name: Build and push docker container
        uses: docker/build-push-action@v2
        with:
          build-args: NODE_ENV=production
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/gladax/admin-ui:latest
      - name: Update production container image
        run: aliyun ecs RunCommand --RegionId 'ap-southeast-3' --Username 'root' --RepeatMode 'Once' --CommandContent 'ZG9ja2VyIHNlcnZpY2UgdXBkYXRlIC0td2l0aC1yZWdpc3RyeS1hdXRoIC0taW1hZ2UgcmVnaXN0cnktaW50bC5hcC1zb3V0aGVhc3QtMy5hbGl5dW5jcy5jb20vZ2xhZGF4L2FkbWluLXVpOmxhdGVzdCBnbGFkYXgtYWRtaW4KCmRvY2tlciBzeXN0ZW0gcHJ1bmUgLWEgLWY=' --Name 'update_prod_admin_container' --Type 'RunShellScript' --ContentEncoding 'Base64' --InstanceId.1 ${{ secrets.ALIYUN_PROD_INSTANCE_ID }}
