name: Build & Push to Stage

on:
  push:
    branches: [stage]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push docker container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/gladax/stage-admin:latest
            ${{ secrets.REGISTRY_URL }}/gladax/stage-admin:${{ github.sha }}
      - name: Update stage container image
        run: aliyun ecs RunCommand --RegionId 'ap-southeast-3' --Username 'root' --RepeatMode 'Once' --CommandContent 'ZG9ja2VyIHNlcnZpY2UgdXBkYXRlIC0td2l0aC1yZWdpc3RyeS1hdXRoIC0taW1hZ2UgcmVnaXN0cnktaW50bC5hcC1zb3V0aGVhc3QtMy5hbGl5dW5jcy5jb20vZ2xhZGF4L3N0YWdlLWFkbWluOmxhdGVzdAoKZG9ja2VyIHN5c3RlbSBwcnVuZSAtYSAtZg==' --Name 'update_stage_api_container' --Type 'RunShellScript' --ContentEncoding 'Base64' --InstanceId.1 ${{ secrets.ALIYUN_STAGE_INSTANCE_ID }}
